<a href="https://colab.research.google.com/github/wynn918/ML/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [ ]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [ ]:
result_ = scaler.fit_transform(data)#combine the fit and transform, will same as the result
scaler.inverse_transform(result)#Can be restored to the original data

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [ ]:
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [ ]:
#When data is too large, use partial_fit()

In [ ]:
#Using numpy to normalization
import numpy as np
x = np.array([[-1,2],[-0.5,6],[0,10],[1,18]])
x_nor = (x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
x_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [ ]:
x_restored = x_nor*(x.max(axis=0)-x.min(axis=0)) + x.min(axis=0)
x_restored

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = StandardScaler()
scaler = scaler.fit(data)
scaler.mean_

array([-0.125,  9.   ])

In [ ]:
scaler.var_

array([ 0.546875, 35.      ])

In [ ]:
x_std = scaler.transform(data)
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [ ]:
print(x_std.mean())
print(x_std.std())

0.0
1.0


In [ ]:
scaler.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [ ]:
scaler.inverse_transform(x_std) 

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])